# Generated by Django 4.0.8 on 2023-04-17 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0001_initial'),
    ]

    operations = [
    ]
