# Generated by Django 4.1.6 on 2023-02-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
