# Generated by Django 4.0.8 on 2023-04-17 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0002_auto_20230417_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='courses',
        ),
        migrations.AddField(
            model_name='collection',
            name='courses',
            field=models.ForeignKey(help_text='select a course for this collection', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursemanagement.course'),
        ),
    ]
