# Generated by Django 4.1.6 on 2023-03-08 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coursemanagement', '0003_assignment_delete_essayassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='due_date',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='word_count',
            new_name='grade',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='essay',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.assignment')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
