# Generated by Django 4.1.6 on 2023-02-14 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userdata_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='username',
        ),
    ]
