# Generated by Django 4.1.6 on 2023-02-15 09:25

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userdata_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='firstname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='lastname',
            field=models.CharField(default=datetime.datetime(2023, 2, 15, 9, 25, 21, 840453, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
