# Generated by Django 4.0.8 on 2023-03-14 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userdata_date_of_birth_userdata_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('STUDENT', 'student')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
