# Generated by Django 4.0.8 on 2023-03-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userdata_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='role',
        ),
        migrations.AddField(
            model_name='userdata',
            name='user',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('STUDENT', 'student')], default='admin', max_length=50),
        ),
    ]
