# Generated by Django 4.0.8 on 2023-03-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userdata_role_userdata_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='user',
            new_name='users',
        ),
    ]
