# Generated by Django 4.0.8 on 2023-03-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_user_userdata_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='users',
            new_name='user',
        ),
    ]
