# Generated by Django 4.0.8 on 2023-03-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_admin_student_remove_userdata_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
