# Generated by Django 4.0.8 on 2023-03-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_admin_admin_name_student_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
