# Generated by Django 4.0.8 on 2023-04-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_userdata_is_staff_alter_userdata_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='name',
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('STUDENT', 'student')], default='admin', max_length=50),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
