# Generated by Django 4.0.8 on 2023-04-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_student_user_remove_userdata_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
